# Generated by Django 4.2.8 on 2024-02-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("city", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("state", models.CharField(max_length=20)),
            ],
        ),
    ]
