# Generated by Django 4.2.8 on 2024-02-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="data",
            name="age",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
